### PR TITLE
chg: Use flask-restx for the API

### PR DESCRIPTION
**Pull request by Rafiot**
Related #136

Just a few changes in order to make the API easier to implement. The tests cases are passing, and it shouldn't change anything for existing tools.

This PR should not be merged at this point, but I find it easier to discuss the upcoming changes with some code.

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by Rafiot** [comment]
alright, the tests aren't passing, but afaik, it's not related to my changes. But I can still fix the issues with the warning lists (I develop that module)

**Comment by Rafiot** [comment]
Okay, so I did a little bit more cleanup on this one.

* New route (`graph`), that expects an encoded URL in the `url` parameter
* Grab the URL directly from the URL Parameters in javascript instead of passing it to the template
* Fix the `PyMISPWarningListsError` exception (you might want an other PR for this one, but I also released a new package for PyMISPWarninglists, fixing the issue)

**Comment by obsidianforensics** [comment]
Looks good, and thanks for fixing the PyMISPWarningListsError and the new package, I'll remove my temp stuff in another PR. 

One thing that's been a problem in the past is URL fragments (#22). I got it to work on the public site by base64-encoding the input URL, but the local app was still dropping it. Could you use `window.location.hash` to pass this along as well, similarly to how you did it with `window.location.search`? It'd be great to get that fixed.

**Comment by Rafiot** [comment]
Good point. It's a bit of a quick and dirty fix, but it seems to work fine.

**Comment by obsidianforensics** [comment]
Just checking, but you are still working on this, right? It's not ready to merge?

**Comment by Rafiot** [comment]
Woops, sorry, I was sidetracked on an other project and totally forgot to update you on that... As a first iteration, I think it's it's good to go (?), but please let me know if you'd like changes. 

Before adding new features, I need to play with it in lookyloo and see what else I'd need.

**Comment by obsidianforensics** [comment]
Looks good to me, thanks for your work on this.

**Comment by Rafiot** [comment]
I'll hopefully be able to work on this integration next month, do you think you can merge it soon-ish? Just so I don't use my own repo.

**Comment by obsidianforensics** [comment]
Yep sorry, I reviewed it but forgot to merge it.

**Comment by Rafiot** [comment]
Thank you!

**Pull request merged**
